import { useState } from 'react';
import GlassCard from './GlassCard';

export default function AppleCalendarSetup() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [status, setStatus] = useState('idle');

  function handleTestConnection() {
    if (!email || !password) {
      setStatus('missing');
      return;
    }

    setStatus('testing');
    window.setTimeout(() => setStatus('ready'), 700);
  }

  return (
    <GlassCard>
      <p className="eyebrow">Apple Calendar</p>
      <h2>Connect Apple Calendar</h2>
      <p className="muted">
        Use your iCloud email and an Apple app-specific password. This is not your normal Apple ID password.
      </p>

      <div className="form-grid">
        <label>
          <span>iCloud email</span>
          <input
            type="email"
            placeholder="name@icloud.com"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
          />
        </label>

        <label>
          <span>App-specific password</span>
          <input
            type="password"
            placeholder="Generated by Apple"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
          />
        </label>
      </div>

      <p className="helper-text">
        Create this in your Apple Account security settings and name it Family Hub. You can revoke it any time from Apple.
      </p>

      <button className="soft-button" onClick={handleTestConnection}>
        {status === 'testing' ? 'Testing…' : 'Test connection'}
      </button>

      {status === 'missing' && <p className="status-message warning">Add your iCloud email and app-specific password first.</p>}
      {status === 'ready' && <p className="status-message success">Ready to discover calendars. Live CalDAV sync comes next.</p>}
    </GlassCard>
  );
}
